package es.caib.sistra.plugins.regtel.impl.caib.cxf.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 14 12:41:46 CEST 2012
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "urn:es:caib:regweb:ws:v1:services", name = "RegwebFacade")
@XmlSeeAlso({es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ObjectFactory.class})
public interface RegwebFacade {

    @ResponseWrapper(localName = "buscarOficinasFisicasDescripcionResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarOficinasFisicasDescripcionResponse")
    @RequestWrapper(localName = "buscarOficinasFisicasDescripcion", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarOficinasFisicasDescripcion")
    @WebResult(name = "buscarOficinasFisicasDescripcionReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ListaResultados buscarOficinasFisicasDescripcion(
        @WebParam(name = "usuario", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String usuario,
        @WebParam(name = "password", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String password,
        @WebParam(name = "filtro", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String filtro,
        @WebParam(name = "tipo", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String tipo
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "anularEntradaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.AnularEntradaResponse")
    @RequestWrapper(localName = "anularEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.AnularEntrada")
    @WebResult(name = "anularEntradaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public boolean anularEntrada(
        @WebParam(name = "parametrosEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS parametrosEntrada,
        @WebParam(name = "anular", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        boolean anular
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "buscarTodosDestinatariosResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarTodosDestinatariosResponse")
    @RequestWrapper(localName = "buscarTodosDestinatarios", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarTodosDestinatarios")
    @WebResult(name = "buscarTodosDestinatariosReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ListaResultados buscarTodosDestinatarios(
        @WebParam(name = "usuario", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String usuario,
        @WebParam(name = "password", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String password
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "buscarDocumentosResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarDocumentosResponse")
    @RequestWrapper(localName = "buscarDocumentos", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarDocumentos")
    @WebResult(name = "buscarDocumentosReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ListaResultados buscarDocumentos(
        @WebParam(name = "usuario", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String usuario,
        @WebParam(name = "password", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String password
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "leerSalidaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.LeerSalidaResponse")
    @RequestWrapper(localName = "leerSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.LeerSalida")
    @WebResult(name = "leerSalidaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS leerSalida(
        @WebParam(name = "parametrosSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS parametrosSalida
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "validarEntradaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ValidarEntradaResponse")
    @RequestWrapper(localName = "validarEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ValidarEntrada")
    @WebResult(name = "validarEntradaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS validarEntrada(
        @WebParam(name = "parametrosEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS parametrosEntrada
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "buscarOficinasFisicasResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarOficinasFisicasResponse")
    @RequestWrapper(localName = "buscarOficinasFisicas", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.BuscarOficinasFisicas")
    @WebResult(name = "buscarOficinasFisicasReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ListaResultados buscarOficinasFisicas(
        @WebParam(name = "usuario", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String usuario,
        @WebParam(name = "password", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String password,
        @WebParam(name = "tipo", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        java.lang.String tipo
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "actualizarSalidaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ActualizarSalidaResponse")
    @RequestWrapper(localName = "actualizarSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ActualizarSalida")
    @WebResult(name = "actualizarSalidaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS actualizarSalida(
        @WebParam(name = "parametrosSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS parametrosSalida
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "grabarEntradaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.GrabarEntradaResponse")
    @RequestWrapper(localName = "grabarEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.GrabarEntrada")
    @WebResult(name = "grabarEntradaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS grabarEntrada(
        @WebParam(name = "parametrosEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS parametrosEntrada
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "actualizarEntradaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ActualizarEntradaResponse")
    @RequestWrapper(localName = "actualizarEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ActualizarEntrada")
    @WebResult(name = "actualizarEntradaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS actualizarEntrada(
        @WebParam(name = "parametrosEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS parametrosEntrada
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "anularSalidaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.AnularSalidaResponse")
    @RequestWrapper(localName = "anularSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.AnularSalida")
    @WebResult(name = "anularSalidaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public boolean anularSalida(
        @WebParam(name = "parametrosSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS parametrosSalida,
        @WebParam(name = "anular", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        boolean anular
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "validarSalidaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ValidarSalidaResponse")
    @RequestWrapper(localName = "validarSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ValidarSalida")
    @WebResult(name = "validarSalidaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS validarSalida(
        @WebParam(name = "parametrosSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS parametrosSalida
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "grabarSalidaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.GrabarSalidaResponse")
    @RequestWrapper(localName = "grabarSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.GrabarSalida")
    @WebResult(name = "grabarSalidaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS grabarSalida(
        @WebParam(name = "parametrosSalida", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroSalidaWS parametrosSalida
    ) throws RegwebFacadeException;

    @ResponseWrapper(localName = "leerEntradaResponse", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.LeerEntradaResponse")
    @RequestWrapper(localName = "leerEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade", className = "es.caib.sistra.plugins.regtel.impl.caib.cxf.model.LeerEntrada")
    @WebResult(name = "leerEntradaReturn", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
    @WebMethod
    public es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS leerEntrada(
        @WebParam(name = "parametrosEntrada", targetNamespace = "urn:es:caib:regweb:ws:v1:model:RegwebFacade")
        es.caib.sistra.plugins.regtel.impl.caib.cxf.model.ParametrosRegistroEntradaWS parametrosEntrada
    ) throws RegwebFacadeException;
}
