alter table ZPE_RPGTPV  add   TPV_ENTIDA           VARCHAR2(100);
alter table ZPE_RPGTPV  add   TPV_IDEPRO           VARCHAR2(100);


-- HAY QUE ACTUALIZAR CON EL CODIGO DE ENTIDAD CORRESPONDIENTE
UPDATE ZPE_RPGTPV SET TPV_ENTIDA = 'XXXX'; 
COMMIT;